import "./style/globals.css";
import { UilMoonEclipse } from "@iconscout/react-unicons";
import SearchBar from "./components/SearchBar";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html>
      <body>
        <div className="bg-blue-900 p-4 flex flex-col items-center justify-center">
          <div className="flex-shrink-0 mb-4">
            <UilMoonEclipse size="60" className="text-yellow-600" />
          </div>
          <h1 className="text-5xl text-white font-bold mb-4">WEATHER REPORT</h1>
          <div>
            <SearchBar />
          </div>
        </div>
        <div>{children}</div>
      </body>
    </html>
	);
}
